# Permalinks
permalink:           pretty

# Setup
title:               Will Stith
tagline:             An Even More Okay Data Science Blog
url:                 http://willstith.github.io
paginate:            2
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Will Stith
  url:               https://twitter.com/makeatwitter
  email:             wstith@alumni.nd.edu

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/willstith

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist

# Page List
pages_list:
  About: '/about'
  Archive: '/archive'
  Feed: '/index.html'
